#!/usr/bin/env bash

# halt on unset variables
set -e 
set -u 

echo "Commencing provisioning process"
echo "-------------------------------"
echo ""
echo "Installation consists of:"
echo "A local private network for 3 hosts on 172.16.80.2, .3, and .4"
echo "Automatic updates to your /etc/hosts for these"
echo ""
echo " ldap.example.com (172.16.80.2) - LDAP server using openLDAP port 389,636"
echo " sp.example.com (172.16.80.3)   - Apache2 port 80,443 with mod_shib"
echo " idp.example.com (172.16.80.4)  - Shibboleth IdP v3, port 443 and connects to LDAP over port 636"
echo ""

IDPInstallerGITRepo="idp-installer-CAF"
export IDPInstallerBase="${PWD}/idp/work/idp-installer-CAF"

PROVMSG="provisioning relevant services to it"

echo "Setting IDPInsallerBase variable to: ${IDPInstallerBase}"

echo "Bringing up ldap.example.com"
	vagrant up ldap --no-provision
	echo "${PROVMSG}"
	vagrant provision ldap --provision-with base,install # debug

echo "Bringing up sp.example.com"
	SSO="eds"
	vagrant up sp  --no-provision
	echo "${PROVMSG}"
	vagrant provision sp --provision-with base,install,config,eds
	SSO=${SSO} vagrant provision sp --provision-with sso

echo "Bringing up the IdP"
	vagrant up idp --no-provision
	echo "${PROVMSG}"
	vagrant provision idp --provision-with base,install


echo "Establishing trust for the SP to trust the IdP"
	vagrant provision sp --provision-with metadata-idp

echo "Establishing trust for the IdP to trust the SP"
	vagrant provision idp --provision-with metadata

echo ""
echo ""
echo "You should be able to do a test login at https://sp.example.com/secure-all"
echo "(Autogenerated self-signed certificates on each install, accept in your browser to see the pages properly)"
echo ""